// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyA8gMOI3T-bHUxwAu-whcHYyMhycJIjSPk",
      authDomain: "planejamentoviagem-351a6.firebaseapp.com",
      projectId: "planejamentoviagem-351a6",
      storageBucket: "planejamentoviagem-351a6.appspot.com",
      messagingSenderId: "531333263383",
      appId: "1:531333263383:web:12e8f12aa83a68dfe56c52",
      measurementId: "G-67SYQLFNSH");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8gMOI3T-bHUxwAu-whcHYyMhycJIjSPk',
    appId: '1:531333263383:android:525f25244f182aa5e56c52',
    messagingSenderId: '531333263383',
    projectId: 'planejamentoviagem-351a6',
    storageBucket: 'planejamentoviagem-351a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjgprr1HCHgNBaQFi8m0VhmNDwtSv5gvM',
    appId: '1:531333263383:ios:2c86b6336e4176c06bb388',
    messagingSenderId: '531333263383',
    projectId: 'planejamentoviagem-351a6',
    storageBucket: 'planejamentoviagem-351a6.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjgprr1HCHgNBaQFi8m0VhmNDwtSv5gvM',
    appId: '1:531333263383:ios:86442f31595c382f6bb388',
    messagingSenderId: '531333263383',
    projectId: 'planejamentoviagem-351a6',
    storageBucket: 'planejamentoviagem-351a6.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
